/**
 * Gift collection taxonomy for the Personalized hub.
 * Images are local files under /public/gifts (always load).
 */

const g = (file) => `/gifts/${file}`

function slug(label) {
  return String(label || '')
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function item(label, imageFile, path) {
  return {
    id: slug(label),
    label,
    image: g(imageFile),
    path: path || `/categories?q=${encodeURIComponent(label)}`,
  }
}

export const giftCollectionGroups = [
  {
    id: 'corporate',
    emoji: '🏢',
    title: 'Corporate Gifts',
    description: 'Welcome kits, client gifts, and branded merchandise for teams.',
    path: '/corporate',
    image: g('corporate.jpg'),
    items: [
      item('Employee Welcome Kits', 'thankyou.jpg', '/corporate/welcome-kits'),
      item('Joining Kits', 'shopping.jpg', '/corporate/joining-kits'),
      item('Client Gifts', 'gift-red.jpg', '/corporate'),
      item('Executive Gifts', 'watch.jpg', '/corporate/executive'),
      item('Promotional Gifts', 'tech.jpg', '/corporate/promo'),
      item('Office Accessories', 'corporate.jpg', '/corporate/office'),
      item('Corporate Gift Hampers', 'hamper.jpg', '/corporate'),
      item('Conference Kits', 'relationship.jpg', '/corporate'),
      item('Event Merchandise', 'celebration.jpg', '/corporate/merchandise'),
      item('Awards & Trophies', 'fashion.jpg', '/corporate'),
      item('Eco-Friendly Gifts', 'eco.jpg', '/categories?q=Eco-Friendly'),
    ],
  },
  {
    id: 'wedding',
    emoji: '💍',
    title: 'Wedding Gifts',
    description: 'Sets, return gifts, and keepsakes for the big day.',
    path: '/functions/wedding',
    image: g('wedding.jpg'),
    items: [
      item('Wedding Gift Sets', 'wedding.jpg', '/functions/wedding'),
      item('Return Gifts', 'gift-red.jpg', '/functions/wedding'),
      item('Bride Gifts', 'flowers.jpg', '/functions/wedding'),
      item('Groom Gifts', 'watch.jpg', '/functions/wedding'),
      item('Bridesmaid Gifts', 'fashion.jpg', '/functions/wedding'),
      item('Groomsmen Gifts', 'thankyou.jpg', '/functions/wedding'),
      item('Wedding Hampers', 'hamper.jpg', '/functions/wedding'),
      item('Invitation Gifts', 'ring.jpg', '/functions/wedding'),
    ],
  },
  {
    id: 'birthday',
    emoji: '🎂',
    title: 'Birthday Gifts',
    description: 'Boxes, sweets, flowers, and personalized surprises.',
    path: '/celebrations/birthday',
    image: g('birthday.jpg'),
    items: [
      item('Birthday Gift Boxes', 'gift-red.jpg', '/celebrations/birthday'),
      item('Cakes', 'cake.jpg', '/celebrations/birthday'),
      item('Chocolates', 'chocolate.jpg', '/celebrations/birthday'),
      item('Flowers', 'flowers.jpg', '/celebrations/birthday'),
      item('Soft Toys', 'kids.jpg', '/celebrations/birthday'),
      item('Personalized Birthday Gifts', 'relationship.jpg', '/personalized'),
      item('Surprise Boxes', 'surprise.jpg', '/surprise'),
    ],
  },
  {
    id: 'anniversary',
    emoji: '❤️',
    title: 'Anniversary Gifts',
    description: 'Romantic picks for couples and shared memories.',
    path: '/celebrations/anniversary',
    image: g('anniversary.jpg'),
    items: [
      item('Couple Gifts', 'anniversary.jpg', '/celebrations/anniversary'),
      item('Personalized Frames', 'relationship.jpg', '/personalized/photo'),
      item('Memory Albums', 'craft.jpg', '/personalized/photo'),
      item('Romantic Gift Boxes', 'gift-red.jpg', '/celebrations/anniversary'),
      item('Flowers & Chocolates', 'flowers.jpg', '/celebrations/anniversary'),
    ],
  },
  {
    id: 'baby',
    emoji: '👶',
    title: 'Baby Gifts',
    description: 'Soft, sweet, and personalized for little ones.',
    path: '/functions/baby-shower',
    image: g('baby.jpg'),
    items: [
      item('Baby Shower Gifts', 'baby.jpg', '/functions/baby-shower'),
      item('Newborn Gift Sets', 'thankyou.jpg', '/functions/baby-shower'),
      item('Kids Toys', 'kids.jpg', '/categories?q=Toys'),
      item('Baby Essentials', 'spa.jpg', '/functions/baby-shower'),
      item('Personalized Baby Gifts', 'relationship.jpg', '/personalized'),
    ],
  },
  {
    id: 'home',
    emoji: '🏠',
    title: 'Home & Living',
    description: 'Decor, aroma, plants, and handmade home accents.',
    path: '/categories?q=Home',
    image: g('home.jpg'),
    items: [
      item('Home Decor', 'home.jpg'),
      item('Wall Art', 'craft.jpg'),
      item('Resin Art', 'handmade.jpg', '/handmade'),
      item('Candles', 'spa.jpg'),
      item('Aroma Products', 'plant.jpg'),
      item('Indoor Plants', 'plant.jpg'),
      item('Decorative Lights', 'decor.jpg'),
    ],
  },
  {
    id: 'handmade-crafts',
    emoji: '🌸',
    title: 'Handmade Crafts',
    description: 'Cards, paintings, crochet, resin, clay, and wood.',
    path: '/handmade',
    image: g('handmade.jpg'),
    items: [
      item('Handmade Cards', 'craft.jpg', '/handmade'),
      item('Handmade Paintings', 'craft.jpg', '/handmade'),
      item('Crochet Products', 'yarn.jpg', '/handmade'),
      item('Resin Crafts', 'handmade.jpg', '/handmade'),
      item('Clay Art', 'pottery.jpg', '/handmade'),
      item('Macrame', 'textile.jpg', '/handmade'),
      item('Wooden Crafts', 'ceramic.jpg', '/handmade'),
    ],
  },
  {
    id: 'hampers',
    emoji: '🍫',
    title: 'Gift Hampers',
    description: 'Chocolate, dry fruit, healthy, luxury, and festival baskets.',
    path: '/store/hamper-builder',
    image: g('hamper.jpg'),
    items: [
      item('Chocolate Hampers', 'chocolate.jpg'),
      item('Dry Fruit Hampers', 'food.jpg'),
      item('Healthy Hampers', 'plant.jpg'),
      item('Luxury Hampers', 'thankyou.jpg'),
      item('Festival Hampers', 'festival.jpg', '/festivals'),
      item('Corporate Hampers', 'corporate.jpg', '/corporate'),
    ],
  },
  {
    id: 'fashion',
    emoji: '💎',
    title: 'Fashion & Accessories',
    description: 'Jewelry, watches, bags, and finishing touches.',
    path: '/categories?q=Fashion',
    image: g('fashion.jpg'),
    items: [
      item('Jewelry', 'fashion.jpg'),
      item('Watches', 'watch.jpg'),
      item('Wallets', 'shopping.jpg'),
      item('Handbags', 'shopping.jpg'),
      item('Sunglasses', 'watch.jpg'),
      item('Perfumes', 'spa.jpg'),
      item('Belts', 'gift-red.jpg'),
    ],
  },
  {
    id: 'tech',
    emoji: '📱',
    title: 'Tech Gifts',
    description: 'Gadgets and accessories they will actually use.',
    path: '/categories?q=Tech',
    image: g('tech.jpg'),
    items: [
      item('Smart Gadgets', 'watch.jpg'),
      item('Bluetooth Speakers', 'tech.jpg'),
      item('Headphones', 'tech.jpg'),
      item('Power Banks', 'corporate.jpg'),
      item('Smart Watches', 'watch.jpg'),
      item('Mobile Accessories', 'shopping.jpg'),
    ],
  },
  {
    id: 'kitchen',
    emoji: '🍽️',
    title: 'Kitchen & Dining',
    description: 'Mugs, bottles, and everyday kitchen favorites.',
    path: '/categories?q=Kitchen',
    image: g('kitchen.jpg'),
    items: [
      item('Coffee Mugs', 'mug.jpg'),
      item('Bottles', 'plant.jpg'),
      item('Lunch Boxes', 'food.jpg'),
      item('Kitchen Accessories', 'home.jpg'),
      item('Tea & Coffee Sets', 'mug.jpg'),
    ],
  },
  {
    id: 'kids',
    emoji: '🧸',
    title: 'Kids & Toys',
    description: 'Play, learn, and soft cuddles for little ones.',
    path: '/categories?q=Kids',
    image: g('kids.jpg'),
    items: [
      item('Educational Toys', 'decor.jpg'),
      item('Soft Toys', 'kids.jpg'),
      item('Activity Kits', 'handmade.jpg'),
      item('Puzzles', 'craft.jpg'),
      item('Stationery', 'relationship.jpg'),
    ],
  },
  {
    id: 'eco',
    emoji: '🌿',
    title: 'Eco-Friendly Gifts',
    description: 'Sustainable picks with a lighter footprint.',
    path: '/categories?q=Eco',
    image: g('eco.jpg'),
    items: [
      item('Bamboo Products', 'eco.jpg'),
      item('Seed Pens', 'plant.jpg'),
      item('Plant Kits', 'plant.jpg'),
      item('Jute Bags', 'textile.jpg'),
      item('Recycled Gifts', 'handmade.jpg'),
    ],
  },
  {
    id: 'festival',
    emoji: '🎉',
    title: 'Festival Gifts',
    description: 'Seasonal edits for every celebration on the calendar.',
    path: '/festivals',
    image: g('festival.jpg'),
    items: [
      item('Diwali Gifts', 'festival.jpg', '/festivals/diwali'),
      item('Pongal Gifts', 'food.jpg', '/festivals/pongal'),
      item('Christmas Gifts', 'gift-red.jpg', '/festivals/christmas'),
      item('New Year Gifts', 'celebration.jpg', '/festivals/new-year'),
      item('Holi Gifts', 'craft.jpg', '/festivals/holi'),
      item('Eid Gifts', 'thankyou.jpg', '/festivals/eid'),
      item('Raksha Bandhan Gifts', 'fashion.jpg', '/festivals/raksha-bandhan'),
      item("Valentine's Gifts", 'anniversary.jpg', '/festivals/valentines'),
    ],
  },
  {
    id: 'relationship',
    emoji: '💖',
    title: 'Relationship Gifts',
    description: 'Thoughtful finds for every person who matters.',
    path: '/relationships',
    image: g('relationship.jpg'),
    items: [
      item('Gifts for Mother', 'flowers.jpg', '/relationships/mother'),
      item('Gifts for Father', 'watch.jpg', '/relationships/father'),
      item('Gifts for Husband', 'thankyou.jpg', '/relationships/husband'),
      item('Gifts for Wife', 'fashion.jpg', '/relationships/wife'),
      item('Gifts for Boyfriend', 'tech.jpg', '/relationships/boyfriend'),
      item('Gifts for Girlfriend', 'anniversary.jpg', '/relationships/girlfriend'),
      item('Gifts for Brother', 'shopping.jpg', '/relationships/brother'),
      item('Gifts for Sister', 'spa.jpg', '/relationships/sister'),
      item('Gifts for Friends', 'party.jpg', '/relationships/best-friend'),
      item('Gifts for Grandparents', 'home.jpg', '/relationships/grandparents'),
      item('Gifts for Teachers', 'mug.jpg', '/relationships/teacher'),
      item('Gifts for Boss', 'corporate.jpg', '/relationships/boss'),
    ],
  },
  {
    id: 'thank-you',
    emoji: '🙏',
    title: 'Thank You Gifts',
    description: 'Say thank you with something they will keep.',
    path: '/thank-you',
    image: g('thankyou.jpg'),
    items: [
      item('Thank You Teacher', 'mug.jpg', '/thank-you/teacher'),
      item('Thank You Doctor', 'spa.jpg', '/thank-you/doctor'),
      item('Thank You Customer', 'gift-red.jpg', '/thank-you/customer'),
      item('Thank You Employee', 'corporate.jpg', '/thank-you/employee'),
      item('Thank You Friend', 'relationship.jpg', '/thank-you/friend'),
      item('Thank You Boss', 'watch.jpg', '/thank-you/boss'),
    ],
  },
  {
    id: 'celebration',
    emoji: '🎈',
    title: 'Celebration Gifts',
    description: 'Milestones, promotions, and big life moments.',
    path: '/celebrations',
    image: g('celebration.jpg'),
    items: [
      item('Congratulations Gifts', 'celebration.jpg', '/celebrations/congratulations'),
      item('Promotion Gifts', 'corporate.jpg', '/celebrations/promotion'),
      item('Graduation Gifts', 'thankyou.jpg', '/functions/graduation'),
      item('Housewarming Gifts', 'home.jpg', '/functions/housewarming'),
      item('Retirement Gifts', 'watch.jpg', '/functions/retirement'),
      item('Farewell Gifts', 'flowers.jpg', '/functions/farewell'),
      item('Achievement Gifts', 'fashion.jpg', '/celebrations/achievement'),
    ],
  },
  {
    id: 'party',
    emoji: '🎊',
    title: 'Party Supplies',
    description: 'Balloons, décor, props, and return-gift ready bags.',
    path: '/categories?q=Party',
    image: g('party.jpg'),
    items: [
      item('Balloons', 'party.jpg'),
      item('Decorations', 'decor.jpg'),
      item('Party Props', 'surprise.jpg'),
      item('Cake Toppers', 'cake.jpg'),
      item('Return Gift Bags', 'shopping.jpg'),
    ],
  },
]

export const GIFT_IMAGE_FALLBACK = g('gift-red.jpg')
